version: '3'
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft_docker
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: 2G
    volumes:
      - ../results/minecraft_data:/data
    restart: unless-stopped

